TRUNCATE cards CASCADE RESTART IDENTITY;
TRUNCATE packages CASCADE RESTART IDENTITY;
TRUNCATE users CASCADE RESTART IDENTITY;
TRUNCATE stack CASCADE RESTART IDENTITY;
TRUNCATE deck CASCADE RESTART IDENTITY;
TRUNCATE tradingdeals CASCADE RESTART IDENTITY;